# Generated by Django 4.1.3 on 2023-02-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
