# Generated by Django 4.1.3 on 2023-02-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_userpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
