# Generated by Django 4.1.3 on 2023-02-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='status',
            new_name='Role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
