# Generated by Django 4.1.3 on 2023-02-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dynamicuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicUser',
            new_name='EmailValidation',
        ),
    ]
