# Generated by Django 4.1.3 on 2023-02-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rolepermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailValidation',
        ),
    ]
