# Generated by Django 4.1.3 on 2023-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_emailvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
