# Generated by Django 4.1.3 on 2023-02-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_blood_group_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('UAE', 'UAE'), ('INDIA', 'INDIA'), ('USA', 'USA'), ('ENGLAND', 'ENGLAND')], max_length=50),
        ),
    ]
