# Generated by Django 3.2.18 on 2023-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_customuser_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
