# Generated by Django 3.2.18 on 2023-03-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_regularization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.PositiveIntegerField(),
        ),
    ]
