# Generated by Django 3.2.18 on 2023-03-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='employee_id',
            field=models.PositiveIntegerField(),
        ),
    ]
