# Generated by Django 3.2.18 on 2023-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularization',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
