# Generated by Django 3.2.18 on 2023-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_regularization_todate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularization',
            name='is_approved',
            field=models.BooleanField(default=None),
        ),
    ]
