# Generated by Django 3.2.18 on 2023-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_regularization_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularization',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
