# Generated by Django 3.2.18 on 2023-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_regularization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularization',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
