# Generated by Django 3.2.18 on 2023-03-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_regularization_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='time',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='accessed_on',
            field=models.DateTimeField(default=None),
        ),
    ]
