# Generated by Django 3.2.18 on 2023-03-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20230315_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='duration',
            field=models.DateTimeField(default=None),
        ),
    ]
