# Generated by Django 3.2.18 on 2023-03-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20230316_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='allholidays',
            name='updated_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allholidays',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
