# Generated by Django 3.2.18 on 2023-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_regularization_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('signin', models.TimeField(default='null', max_length=100)),
                ('signout', models.TimeField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=50)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
