# Generated by Django 3.2.18 on 2023-03-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
