# Generated by Django 3.2.18 on 2023-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20230323_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
