# Generated by Django 3.2.18 on 2023-03-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_attendance_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
