# Generated by Django 3.2.18 on 2023-03-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_leaves_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='email',
        ),
    ]
