# Generated by Django 3.2.18 on 2023-03-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_customuser_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularization',
            name='applied_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
