# Generated by Django 3.2.18 on 2023-03-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_allholidays_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allholidays',
            name='emp',
        ),
    ]
