# Generated by Django 3.2.18 on 2023-03-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_allholidays_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
