# Generated by Django 3.2.18 on 2023-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
