# Generated by Django 3.2.18 on 2023-04-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_customuser_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
