# Generated by Django 3.2.18 on 2023-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
