# Generated by Django 3.2.18 on 2023-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_customuser_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hr',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
