# Generated by Django 3.2.18 on 2023-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_alter_customuser_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
