# Generated by Django 3.2.18 on 2023-04-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_alter_region_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='worklocation',
        ),
    ]
