# Generated by Django 3.2.18 on 2023-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0068_rename_country_region_worklocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
