# Generated by Django 3.2.18 on 2023-04-12 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_alter_customuser_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
