# Generated by Django 3.2.18 on 2023-04-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_emailvalidation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidation',
            name='user',
        ),
    ]
