# Generated by Django 3.2.18 on 2023-04-12 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_emailvalidation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
