# Generated by Django 3.2.18 on 2023-04-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20230413_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalidation',
            name='date_joined',
        ),
    ]
