# Generated by Django 3.2.18 on 2023-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_auto_20230413_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidation',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
