# Generated by Django 3.2.18 on 2023-04-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_emailvalidation_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.emailvalidation'),
        ),
    ]
