# Generated by Django 3.2.18 on 2023-04-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_alter_attendance_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularization',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.emailvalidation'),
        ),
    ]
