# Generated by Django 4.1.5 on 2023-04-17 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0084_alter_leaves_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailvalidation",
            name="Leaves_taken",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="leaves",
            name="Total_days_applying_for",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="leaves",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaves",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
