# Generated by Django 4.1.5 on 2023-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0085_emailvalidation_leaves_taken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaves",
            name="F_session_1",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="leaves",
            name="F_session_2",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="leaves",
            name="T_session_1",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="leaves",
            name="T_session_2",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
