# Generated by Django 4.1.5 on 2023-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0086_leaves_f_session_1_leaves_f_session_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaves",
            name="To_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
