# Generated by Django 4.1.5 on 2023-04-24 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0087_leaves_to_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leavetype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leavetype", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Leavebalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alloated", models.DecimalField(decimal_places=1, max_digits=3)),
                ("balance", models.DecimalField(decimal_places=1, max_digits=3)),
                (
                    "leaves_taken",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                (
                    "emp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leavebalances",
                        to="app.emailvalidation",
                    ),
                ),
                (
                    "leavetype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balancedleavetype",
                        to="app.leavetype",
                    ),
                ),
            ],
        ),
    ]
