# Generated by Django 4.1.5 on 2023-04-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0089_remove_leaves_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaves",
            name="Leave_type",
            field=models.CharField(default="casual", max_length=100),
            preserve_default=False,
        ),
    ]
