# Generated by Django 4.2 on 2023-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_authenticationlog_remove_role_group_role_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('leavetype', 'Leave Type')],
            },
        ),
    ]
